export default {
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    UPDATE_ITEM:'UPDATE_ITEM',
    APPLY_FILTER: 'APPLY_FILTER',
    GET_BEER_LIST: 'GET_BEER_LIST',
    UPDATE_BEER_TEMPERATURE: 'UPDATE_BEER_TEMPERATURE'
}